# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yard-struct}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Edgar"]
  s.date = %q{2010-05-07}
  s.description = %q{yard-struct allows users to document their classes created through Struct.new using a simple, familiar syntax and @member tag.}
  s.email = %q{michael.j.edgar@dartmouth.edu}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/yard-struct.rb",
     "lib/yard-struct/legacy_handler.rb",
     "lib/yard-struct/modern_handler.rb",
     "lib/yard-struct/shared_methods.rb",
     "lib/yard-struct/tag_handler.rb",
     "spec/examples/example_helper.rb",
     "spec/examples/examples/simple_struct.rb",
     "spec/examples/examples/struct_with_docs.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/yard-struct_spec.rb",
     "yard-struct.gemspec"
  ]
  s.homepage = %q{http://github.com/michaeledgar/yard-struct}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{YARD plugin for documenting auto-generated members of Struct subclasses.}
  s.test_files = [
    "spec/examples/example_helper.rb",
     "spec/examples/examples/simple_struct.rb",
     "spec/examples/examples/struct_with_docs.rb",
     "spec/spec_helper.rb",
     "spec/yard-struct_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yard>, [">= 0.4.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<yard>, [">= 0.4.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<yard>, [">= 0.4.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end
